### PR TITLE
Posix: Do not treat arguments as `FilePath`

### LINKED ISSUE #319: NUL byte disallowed in arguments
The following program worked just fine when compiled with GHC <9.8:
```haskell
module Main (main) where

import System.Process

main :: IO ()
main = callProcess "echo" ["foo\0bar"]
```
Compiled with GHC >=9.8 it outputs the following runtime error:
```
*** Exception: /usr/bin/echo: checkForInteriorNuls: invalid argument (FilePaths must not contain internal NUL code units.)
```

The reason is that `process` also treats the arguments as `FilePath`: https://github.com/haskell/process/blob/d74bba244d9d7c83b3a0ef5159b4e2e0fa7df07b/System/Process/Posix.hs#L139 (Linking to the POSIX implementation here since I am running Linux.)
The `System.Posix.Internals.withFilePath` function referenced there checks for internal NULL characters since `base >4.19` due to the accepted CLC propsal https://github.com/haskell/core-libraries-committee/issues/144.

### PR DESCRIPTION
**Pull request by mmhat**
Fixes #319

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
This looks pretty plausible to me, but I'm not an expert with the low level details. There are various people who are better qualified. Perhaps one of them can chime in.

@bgamari @hasufell @snoyberg @Mistuke (or someone else?)

**Comment by hasufell** [comment]
There are two differences:

1. `withFilePath` uses `getFileSystemEncoding`, `withCString` uses `getForeignEncoding`
2. `withFilePath` checks for interior nulls now (not sure since which base version) and barfs out in case it finds any

Tbh, all of those s*ck. But that's another discussion: https://github.com/haskell/process/issues/252

File: System/Process/Posix.hs [hunk 1]
```diff
@@ -136,7 +136,9 @@ createProcess_Internal fun
    maybeWith withFilePath mb_cwd $ \pWorkDir ->
    maybeWith with mb_child_group $ \pChildGroup ->
    maybeWith with mb_child_user $ \pChildUser ->
-   withMany withFilePath (cmd:args) $ \cstrs ->
+   withFilePath cmd $ \cmdstr ->
+   withMany withCString args $ \argstrs -> do
```
Comment (Mistuke) [inline System/Process/Posix.hs:140]: On Windows this would be wrong, it needs to be `withCWString` otherwise it's encoded as 8-byte string rather than 16-bytes.

Comment (mmhat) [reply System/Process/Posix.hs:140]: @Mistuke Thanks for the feedback; Then `withCWString` is indeed the correct choice as I suspected here: https://github.com/haskell/process/issues/319#issuecomment-2184005410

**Comment by mmhat** [comment]
> 2. `withFilePath` checks for interior nulls now (not sure since which base version) and barfs out in case it finds any

I think it is since `base-4.18.0.0` (GHC 9.6.1).

If there are no further objections: Who is willing to merge this?

File: System/Process/Posix.hs (hunk 1 above)
Comment (tomjaguarpaw) [reply System/Process/Posix.hs:140]: What is the conclusion of this exchange? On Windows it would be wrong, but it's not Windows, right? It's POSIX. So is `withCString` indeed right in this case?

Comment (hasufell) [reply System/Process/Posix.hs:140]: > What is the conclusion of this exchange? On Windows it would be wrong, but it's not Windows, right? It's POSIX. So is `withCString` indeed right in this case?

Windows is already correct:

https://github.com/haskell/process/blob/302b43a2e0c514a6ad86cbc402c60bf7f86878e2/System/Process/Windows.hsc#L185

This PR can be merged.

**Comment by tomjaguarpaw** [comment]
OK, released as https://hackage.haskell.org/package/process-1.6.22.0. Thanks @mmhat!
