### PR TITLE
Fix #46

### LINKED ISSUE #46: waitForProcess race condition
```
    -- don't hold the MVar while we call c_waitForProcess...
    -- (XXX but there's a small race window here during which another
    -- thread could close the handle or call waitForProcess)
```

This is a small race condition indeed, but today I managed to stumble over it, on a Linux system. I have a situation where 2 threads both need to wait for the same process to exit, so both call waitForProcess. One of the threads would then fairly reliably crash with "waitForProcess: does not exist (No child processes)"

Of course, I can work around it in my code by adding my own locking so only 1 thread calls waitForProcess on a process at a time. It could be similarly fixed in System.Process.. add another MVar to ProcessHandle, and make waitForProcess use it to prevent concurrent calls to c_waitForProcess

### PR DESCRIPTION
**Pull request by charles-cooper**
Previously an exception was being thrown when multiple threads were
blocking on waitForProcess due to inconsistent handling of the return
code of `waitpid`:

"If more than one thread is suspended in waitpid() awaiting termination
of the same process, exactly one thread returns the process status at
the time of the target child process termination. The other threads
return -1, with errno set to ECHILD."

`getProcessExitCode` was handling the ECHILD case by returning 1, but
`waitForProcess` was returning (-1) in all cases. For consistency this
commit follows the approach in getProcessExitCode, returning 1 to the
caller of c_waitForProcess if errno is ECHILD, thus avoiding throwing
an exception in the calling code.

Fixes #46

(An alternative fix could protect all calls to waitpid with an MVar, thus avoiding ECHILD altogether. I ended up settling on this fix because it follows the style in the rest of the library and fixes the bug with minimal code change.)

### CODE REVIEW

**Comment by charles-cooper** [comment]
See reproduction of the bug at https://gist.github.com/charles-cooper/95bdf602c410ec7ebb531b61c8b91be2 (needs `-threaded` and `+RTS -N`)

**Comment by snoyberg** [comment]
I'm not very familiar with this part of the C code. @simonmar, you appear to have been the last person to modify that bit of code. Would you be able to do a review and see if this change makes sense?

@charles-cooper If this works, I think it would make sense to update the comment about the race condition as well.

**Comment by simonmar** [comment]
The fix looks good.  Ideally we should have a test too, though.

**Comment by charles-cooper** [comment]
Thanks! I can add a test -- where is an appropriate place to put the test?

After thinking about deleting the comment, I realized there is still a potential problem in the calling code. It basically only works because a) the acquisition of the lock in https://github.com/haskell/process/blob/master/System/Process.hsc#L594 occurs in FIFO order, and b) if the operating system allocates CPU time first to the thread that gets the exit code. If either of assumptions fails to hold, there is a race condition where one of the threads that received an ECHILD could erroneously set the exit code in the ClosedHandle to 0. Granted these are both reasonable assumptions -- but to my knowledge not *guaranteed* by the semantics of the calls.

.. How should we proceed / Is this an acceptable 'gotcha'? Or should we protect calls to `waitpid` despite the possible performance hit.

**Comment by simonmar** [comment]
Hmm, that's a good point.

I'm actually tempted to just not "fix" this bug, and say that we don't support `waitForProcess` for the same process from multiple threads.  The proper fix is complex and would add overhead to all callers.

**Comment by charles-cooper** [comment]
Just so all options are on the table, the last option I've considered is to encode the information about `ECHILD` in the return value of `c_waitForProcess`, then the caller can decide what to do upon inspection of the return value (right now `1` vs `0`). Somehow this seems less-than-optimal because suddenly everybody writing / modifying the C functions needs to be very disciplined about what they return.

**Comment by charles-cooper** [comment]
@snoyberg Anything I can do to help move this forward?

**Comment by simonmar** [comment]
@charles-cooper I'm tempted to not do anything about this.  What would be the impact of that for you?  It's not hard to work around at the application level, and I would question why you're calling waitForProcess for the same process on different threads anyway.

**Comment by charles-cooper** [comment]
Well to be fair, it's quite confusing that `waitForProcess` is not thread-safe. I believe it's no less reasonable to have more than one thread wait on a process as it is to have more than one thread wait on some mutex.

Furthermore, although it can be worked around in application code -- all correct application code must eventually implement the same fix (after coming across the problem, doing research, working around, etc)! It will save a lot of headaches for application developers if the library just implements the fix :).

To conclude, I think it is important to fix this one way or another, even if it is at some slight performance cost (or we can even avoid the performance cost with more complicated logic). If users want more performance they can use a lower level library - as it stands, it is quite a gotcha that the primary `process` library most application developers will be using is not thread-safe.

**Comment by snoyberg** [comment]
@simonmar In my own experience, I've had to work around this very issue as well. In fact, in both streaming-commons and typed-process, I've explicitly worked around this bug. It does seem to be that expecting all users of the API to be aware of this and work around it is inferior to providing an API that is thread-safe.

**Comment by simonmar** [comment]
Yeah, I tend to agree, but the context has fallen out of my cache here.  I think my worry was about the cost of implementing the fix.

It sounds like we should have one lock in Haskell preventing multiple threads from calling `waitpid` on the same pid.  I presume I didn't want to hold the main `MVar` because it would prevent another thread from doing `terminateProcess` or something else, so maybe we need a separate `MVar`.

**Comment by charles-cooper** [comment]
Just to recap, the options I see are -
1. Go with the fix in this PR. This has the advantage of being consistent with the behavior of `getProcessExitCode` (https://github.com/charles-cooper/process/blob/d67484fe64a9a42e7daf944a9396b4ec46c060f3/cbits/runProcess.c#L388-L392), reasonably unobtrusive, no performance overhead, and correct given certain reasonable assumptions about the OS implementation, at the very least kicking the ball down the road a little.
2. Protect all calls to `waitForProcess` (and also, `getProcessExitCode`) with an extra lock of some sort. This has the benefit of being obviously correct, but requires modifying more of the codebase and may have a performance cost.
3. Encode the `ECHILD` condition in the return value of `waitForProcess` and `getProcessExitCode` and catch the behavior in the caller. This has the advantage of being correct at very little performance cost but resulting in slightly trickier to maintain code (since somebody modifying the C API has to be more careful about what they return).

I'm happy to implement any of these which is deemed most acceptable.

**Comment by simonmar** [comment]
(1) has a race condition (as you pointed out earlier), so we can't go with that
(3) what would you do if the call returns ECHILD?  You have to go into some kind of busy-wait loop waiting for the thread with the exit code to store it in the ProcessHandle.  That doesn't seem good either.  

In fact, any solution that allows N thread to be in waitpid() is going to suffer from this problem, because N-1 threads will have to synchronise with the one thread that has the exit code.  And be very careful to prevent the thread with the exit code from dying, e.g. from an async exception, before it stores the exit code.

Putting Haskell-side synchronisation around the waitpid() seems like the only option.

**Comment by charles-cooper** [comment]
> (3) what would you do if the call returns ECHILD? You have to go into some kind of busy-wait loop waiting for the thread with the exit code to store it in the ProcessHandle. That doesn't seem good either.

Since the operation of storing the exit code should be very fast, we can just use the existing `MVar ProcessHandle__` for the synchronization (whereas synchronizing on it for the `waitpid` is prohibitive since `waitpid` could indefinitely block all other users of the `Process`). While technically one would have to busy-wait, given the semantics of `takeMVar` as having FIFO wakeup, it would synchronize at most two times instead of exactly once as it does now.

**Comment by charles-cooper** [comment]
> And be very careful to prevent the thread with the exit code from dying, e.g. from an async exception, before it stores the exit code.

You raise a good point. There is a "small race window" between returning from `waitpid` and being able to mask async exceptions for the purpose of storing the exit code.

**Comment by charles-cooper** [comment]
I think it's solvable, though I'm not sure it's worth the complexity. I'm not terribly familiar with the semantics of `mask` but it would seem it's possible to do something like
```haskell
mask $ \restore -> do
  restore c_waitForProcess `onException`
    if exited && exitCodeGood then writeExitCode else return ()
  ...
```

**Comment by charles-cooper** [comment]
I rewrote it with an MVar for waitpid. Let me know if that's OK and I can clean up the commit messages and such (according to the style guide? is there one?)

File: System/Process.hs [hunk 1]
```diff
@@ -584,14 +584,11 @@ detail.
 waitForProcess
   :: ProcessHandle
   -> IO ExitCode
-waitForProcess ph@(ProcessHandle _ delegating_ctlc) = do
+waitForProcess ph@(ProcessHandle _ delegating_ctlc _) = lockWaitpid $ do
   p_ <- modifyProcessHandle ph $ \p_ -> return (p_,p_)
   case p_ of
     ClosedHandle e -> return e
     OpenHandle h  -> do
-        -- don't hold the MVar while we call c_waitForProcess...
```
Comment (simonmar) [inline System/Process.hs]: This is still somewhat relevant - we want `getProcessExitCode` to work while there is a concurrent `waitForProcess`.

File: System/Process.hs [hunk 2]
```diff
@@ -616,6 +613,7 @@ waitForProcess ph@(ProcessHandle _ delegating_ctlc) = do
 #else
         return $ ExitFailure (-1)
 #endif
+  where lockWaitpid m = withMVar (waitpidLock ph) $ \() -> m
```
Comment (simonmar) [inline System/Process.hs]: Let's add a comment here to explain the problem and the solution, and point to this ticket.

**Comment by charles-cooper** [comment]
@simonmar how is it looking?

**Comment by simonmar** [comment]
Fine by me.  I don't usually merge into this repo though, @snoyberg?

**Comment by snoyberg** [comment]
I'll look in a few days, just juggling a newly released package right now.

**Comment by snoyberg** [comment]
It looks like the issue around `getProcessExitCode` remains unresolved. Shouldn't it respect the lock as well?

**Comment by charles-cooper** [comment]
My original comment about `getProcessExitCode` was incorrect, it shouldn't have to wait for a call to `waitForProcess` to return since `waitForProcess` is blocking. Since the `ProcessHandle__` is protected by a lock, `waitForProcess` and `getProcessExitCode` can't modify the process handle state at the same time; the worst case is that a thread calling `getProcessExitCode` will just view the process as still running and have to call `getProcessExitCode` again.

**Comment by snoyberg** [comment]
But `waitForProcess` doesn't actually hold the `ProcessHandle__` `MVar` while blocking, so it looks like the race condition between the two absolutely remains (as per Simon's comment). In typed-process I resolved this by having a dedicated thread calling `waitForProcess` and filling a `TMVar`, and then have the equivalent of `getProcessExitCode` work on that `TMVar`.

**Comment by charles-cooper** [comment]
I'm not sure which race condition is being referred to here. I think simon was just referring to leaving the comment in - we don't hold the lock while `waitForProcess` is blocking on `waitpid` so that `getProcessExitCode` still returns.

**Comment by snoyberg** [comment]
With your changes in place, what is preventing the following from occurring:

1. Thread A calls `waitForProcess` 
2. Thread A calls `modifyProcessHandle ph $ \p_ -> return (p_,p_)` within `waitForProcess` and gets an `OpenHandle`
3. Thread B calls `getProcessExitCode`, the process has exited already, it completes the C call, and fills the `MVar` with a `ClosedHandle`
4. Thread A now continues and calls `c_waitForProcess`, which will no longer work since the entry in the process table has already been cleared

**Comment by charles-cooper** [comment]
Good catch. Perhaps I should bring back https://github.com/charles-cooper/process/commit/5b99d45103d1edf6f596c353f548221d897db4cf?

**Comment by charles-cooper** [comment]
(In addition to the waitpid lock which we have agreed is necessary)

**Comment by snoyberg** [comment]
I'm not confident enough in my understanding of the C code to know that that's safe. However, I'm pretty sure it's still susceptible to a race condition, specific of where a new process is created with the same PID as the previous process. I'd feel more comfortable moving all of the logic into the Haskell code itself.

**Comment by charles-cooper** [comment]
I see! Sounds like it will work better with STM. I'll see what I can whip up this weekend.

**Comment by snoyberg** [comment]
Since it's a boot library, I think using the stm package may be a non-starter here (someone can correct me if I'm wrong hopefully). I suppose using `GHC.Conc` from `base` directly may be acceptable.

**Comment by charles-cooper** [comment]
Actually I think simply checking from the `getProcessExitCode` if the `waitpidLock` is held should be enough of an indication that the process hasn't exited yet.

**Comment by charles-cooper** [comment]
@snoyberg I think https://github.com/haskell/process/pull/58/commits/c722d8b85568d2185dbe716a9988697eccb27e56 should fix the race condition you outlined in https://github.com/haskell/process/pull/58#issuecomment-279772508.

**Comment by charles-cooper** [comment]
Maybe it would be OK to use this `tryTakeMVar` with just the original `ProcessHandle__` `MVar` and not bother with the extra lock. Would that have any subtle consequences I am missing?

**Comment by charles-cooper** [comment]
I guess that would probably block `interruptProcessGroupOf` from working

**Comment by snoyberg** [comment]
Yeah, I noticed that too. I can't think of a way to truly avoid a race
condition with process killing, however.

File: System/Process.hs [hunk 3]
```diff
@@ -663,6 +663,23 @@ getProcessExitCode ph@(ProcessHandle _ delegating_ctlc _) = do
...
+          tryLockWaitpid :: IO (Maybe ExitCode) -> IO (Maybe ExitCode)
+          tryLockWaitpid action = bracket acquire release between
+            where
+              acquire   = tryTakeMVar (waitpidLock ph)
+              release m = case m of
+                Nothing -> return ()
+                Just () -> putMVar (waitpidLock ph) ()
+              between m = case m of
+                Nothing -> return Nothing
+                Just () -> do     action
```
Comment (simonmar) [inline System/Process.hs]: extra `do` and whitespace

File: System/Process.hs (hunk 1 above)
Comment (snoyberg) [inline System/Process.hs]: This has now been addressed with the changes to `getProcessExitCode` recently added.

**Comment by snoyberg** [comment]
Thanks @charles-cooper and @simonmar!
