### PR TITLE
Call initgroups before setuid

### LINKED ISSUE #149: Process fails to call initgroups before setuid
On POSIX platforms we use `setuid` and `setgid` to change the child process's uid and gid. This is most often used to drop privileges. However, `setgid` merely changes a processes' primary group; it does not drop the other groups which the process may also be a member of. To do this we must call `initgroups`.

The fact that we fail to call `initgroups` means that we may not be dropping as many privileges as the user expects.

### PR DESCRIPTION
**Pull request by bgamari**
This fixes a potential privilege escalation issue (or, more precisely, privileges not being dropped when this was the user's intent) where the groups of the spawning process's user would be incorrectly retained due to a missing call to `initgroups`.

This also fixes an incorrect case fallthrough in the error message lookup logic.

Fixes #149.

### CODE REVIEW

**Comment by bgamari** [comment]
This was originally reported at https://github.com/ndmitchell/ghcid/issues/261.

**Comment by snoyberg** [comment]
I'm surprised that appveyor is failing on this. I'll try rebasing on `master` and see if that results in something else.

File: include/runProcess.h [hunk 1]
```diff
@@ -21,6 +21,8 @@
 
 #include <unistd.h>
 #include <sys/types.h>
+#include <pwd.h>
```
Comment (snoyberg) [inline include/runProcess.h]: I think this should be conditional on the OS _not_ being Windows, IIUC that's where the AppVeyor failure is coming from.

File: cbits/runProcess.c [hunk 2]
```diff
@@ -182,6 +185,22 @@ runInteractiveProcess (char *const args[],
...
+            // However, to do this we must know the username of the user we are
+            // switching to.
+            struct passwd pw;
+            struct passwd *res = NULL;
+            int buf_len = sysconf(_SC_GETPW_R_SIZE_MAX);
+            char *buf = malloc(buf_len);
+            gid_t suppl_gid = childGroup ? *childGroup : getgid();
+            if ( getpwuid_r(*childUser, &pw, buf, buf_len, &res) != 0) {
+                childFailed(forkCommunicationFds[1], forkGetpwuidFailed);
+            } else if (res == NULL) {
```
Comment (snoyberg) [inline cbits/runProcess.c]: The mixing of `else if` and `if` makes the code confusing, at least IMO. `childFailed` will cause the program to exit regardless, so the `else` isn't strictly necessary, but it arguably helps with readability. I don't care too much one direction or the other, but I'd prefer to see the code be consistent.

If there's a reason for using `else if` in just one of the checks, please clarify, ideally with an inline comment.

**Comment by juhp** [comment]
I have tested Ben's patch with ghc-8.6.5, process:initgroups, and cabal-install-2.2 and can confirm that with the patched process, ghcid-0.7.5 has `initgroups`. Thanks @bgamari for this.

```
[ f31container | ~/process:initgroups ] $ readelf -a ~/.cabal/bin/ghcid|grep initgroups
0000008ba160  005700000007 R_X86_64_JUMP_SLO 0000000000000000 initgroups@GLIBC_2.2.5 + 0
    87: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND initgroups@GLIBC_2.2.5 (4)
```

File: cbits/runProcess.c (hunk 2 above)
Comment (bgamari) [reply cbits/runProcess.c]: Indeed looking back at this I can't imagine what I was thinking. This `else if` looks just plain wrong.

Comment (bgamari) [reply cbits/runProcess.c]: Ahh, no, it's not wrong but indeed the `else` isn't necessary. Fixed.

File: include/runProcess.h (hunk 1 above)
Comment (bgamari) [reply include/runProcess.h]: Strange how `unistd.h` is available on Windows yet `pwd.h` is not. Regardless, this is now properly guarded.

**Comment by juhp** [comment]
Seems to build okay on Windows now :+1: 
(Not quite sure why lts-11 keep failing but does seems related?)

**Comment by bgamari** [comment]
@snoyberg, done.
